# -*- coding: utf-8 -*-
"""S&C_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXDsSRW3RyNZWBTjfdjXZNgt_J4txWhj

Download of the dataset from kaggle
"""

#Download the latest version of the dataset "Proton Collision 13TeV"
import kagglehub

path = kagglehub.dataset_download("brsdincer/proton-collision-image-set")

print("Path to dataset files:", path)

"""Loading train and test datasets"""

import os
import tensorflow as tf

#Define directory paths
train_dir = os.path.join(path, "Proton Collision 13TeV", "Train")
test_dir = os.path.join(path, "Proton Collision 13TeV", "Test")

#Set image dimensions and batch size
IMG_SIZE = (32, 32)
BATCH_SIZE = 256

#Load train dataset
train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical"
)

#Load test dataset
test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical"
)

"""Dataset normalization and speed optimization


"""

from tensorflow.keras import layers

#Define pixel normalization layer
normalization_layer = layers.Rescaling(1.0 / 255)

#Convert images to float32 for model compatibility
def preprocess(image, label):
    image = tf.cast(image, tf.float32)
    return image, label

#Optimization for GPU speed
train_ds = train_ds.map(preprocess).cache().shuffle(1000).prefetch(tf.data.AUTOTUNE)
test_ds = test_ds.map(preprocess).cache().prefetch(tf.data.AUTOTUNE)

"""CNN model architecture and compilation"""

from tensorflow.keras import models, optimizers

#Construct the sequential model
model = models.Sequential([
    #Input layer accepting 32x32 spatial resolution images with 3 color channels
    layers.Input(shape=(32, 32, 3)),

    #Normalize pixel values from [0, 255] to [0.0, 1.0] range
    layers.Rescaling(1./255),

    #Blocks
    layers.Conv2D(32, (3, 3), padding='same', activation='relu', kernel_initializer='he_normal'),
    layers.Conv2D(32, (3, 3), padding='same', activation='relu', kernel_initializer='he_normal'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), padding='same', activation='relu', kernel_initializer='he_normal'),
    layers.Conv2D(128, (3, 3), padding='same', activation='relu', kernel_initializer='he_normal'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25),

    layers.Flatten(),
    layers.Dense(256, activation='relu', kernel_initializer='he_normal'),
    layers.Dropout(0.35),
    layers.Dense(3, activation='softmax')
])

#Configure the Adam optimizer with an initial learning rate suited for small batch updates
optimizer = optimizers.Adam(learning_rate=5e-4)

#Compile model with categorical cross-entropy loss for multi-class classification
model.compile(
    optimizer=optimizer,
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

#Display network architecture parameters
model.summary()

"""Model training"""

from tensorflow.keras.callbacks import ReduceLROnPlateau

#Dynamic learning rate to avoid validation loss plateau
lr_scheduler = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=2,
    min_lr=1e-5,
    verbose=1
)
#Execute training
history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=15,
    callbacks=[lr_scheduler]
)

"""Plotting training history curves"""
import matplotlib 

matplotlib.use('Agg') #to let docker riproduce charts
import matplotlib.pyplot as plt

#Extract accuracy and loss history
acc = history.history["accuracy"]
val_acc = history.history["val_accuracy"]
loss = history.history["loss"]
val_loss = history.history["val_loss"]

epochs_range = range(len(acc))

#Accuracy and loss plots
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label="Train accuracy")
plt.plot(epochs_range, val_acc, label="Validation accuracy")
plt.legend(loc="lower right")
plt.title("Train and validation accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label="Train loss")
plt.plot(epochs_range, val_loss, label="Validation loss")
plt.legend(loc="upper right")
plt.title("Train and validation loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")

plt.tight_layout()
plt.savefig('chart_accuracy.png') 
plt.close()                         

"""Confusion matrix"""

import seaborn as sns
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

#Extract true labels and predictions
y_true = []
y_pred_probs = []

for images, labels in test_ds:
    preds = model.predict(images, verbose=0)
    y_pred_probs.append(preds)
    y_true.extend(np.argmax(labels.numpy(), axis=1))

y_pred_probs = np.vstack(y_pred_probs)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.array(y_true)

#Define class names for LHC jet signals
class_names = ["QCD", "TTbar", "WJets"]

#Generate precision, recall, and F1-score
print("\n--- CLASSIFICATION REPORT ---")
print(classification_report(y_true, y_pred, target_names=class_names, digits=4))

#Compute and plot confusion matrix
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.savefig('confusion_matrix.png') 
plt.close()

"""Prediction and display of 5 jet images"""

#Predict and display the first 5 jet images from a test batch
for images, labels in test_ds.take(1):
    predictions = model.predict(images, verbose=0)

    plt.figure(figsize=(15, 3))
    for i in range(5):
        plt.subplot(1, 5, i + 1)

        plt.imshow(images[i].numpy().astype("uint8"))

        true_label = class_names[np.argmax(labels[i])]
        pred_label = class_names[np.argmax(predictions[i])]
        confidence = 100 * np.max(predictions[i])

        color = "green" if true_label == pred_label else "red"

        plt.title(
            f"True: {true_label}\nPred: {pred_label}\n({confidence:.1f}%)",
            color=color,
            fontsize=10
        )
        plt.axis("off")

    plt.tight_layout()
    plt.savefig('example.png') 
    plt.close()
break
